Neos:
  Flow:
    http:
      middlewares:
        flowpackFusionTracingCheckEnabled:
          position: 'start 999'
          middleware: 'Flowpack\Fusion\Tracing\Http\Middleware\CheckEnabledMiddleware'
