Neos:
  Flow:
    http:
      chain:
        'preprocess':
          chain:
            'flowpackFusionTracingCheckEnabled':
              component: 'Flowpack\Fusion\Tracing\Http\CheckEnabledComponent'
